name: foody
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_zoom_drawer: ^3.2.0
  gap: ^3.0.1
  get_it: ^7.6.7
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  scroll_page_view: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true # Add this line
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/json/
  fonts:
    - family: Sen
      fonts:
        - asset: assets/font/Sen-Bold.ttf
          weight: 700
        - asset: assets\font\Sen-ExtraBold.ttf
          weight: 900
        - asset: assets\font\Sen-Medium.ttf
          weight: 500
        - asset: assets\font\Sen-Regular.ttf
          weight: 400
        - asset: assets\font\Sen-SemiBold.ttf
